repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-added-large-files
    - id: check-toml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.241'
  hooks:
    - id: ruff
      args: ["--fix"]
