name: build wheel

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - run: pip install git+https://github.com/nvaytet/quest.git
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: x86_64
        manylinux: auto
        args: --release --out dist -i python3.10
    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
        
